### ISSUE TITLE
你好 可以选择使用本地存储吗  

### ISSUE THREAD

**Issue by Yakumo-Yukari** [da34/blogs#2]
七牛需要备案才能用  那么如果没有备案的可以选择本地存储吗？

**Comment by da34** [comment]
目前是不支持本地的，最近后端在重新设计，大概一周这样，会支持本地和七牛云的

**Comment by Yakumo-Yukari** [comment]
> 目前是不支持本地的，最近后端在重新设计，大概一周这样，会支持本地和七牛云的

好的  谢谢 想用你这项目搭建个博客  对了 为什么不把分类加入到导航栏呢
